version: "3"

services:
  app:
    build: .
    depends_on:
      - database
    container_name: feature_flags_service
    volumes:
      - .:/feature_flags_service
    ports:
      - 3000:3000
    command: sh -c "bundle exec rake db:setup && bundle exec rerun 'rackup -p 3000'"
    env_file:
      - .env
    stdin_open: true
    tty: true

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./config/db:/var/lib/postgresql/config/db
    container_name: roda_db

volumes:
  postgres-data:
