<%= ENV['RACK_ENV'] %>:
  adapter: postgres
  timeout: 180000
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>
  database: <%= ENV['PGDATABASE'] %>
